// <auto-generated />
namespace Revenda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterTableUsuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterTableUsuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201611130546078_AlterTableUsuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
